name: Pipeline Lab Final Byron

on:
  push:
    branches: 
      - feature*

permissions:
  contents: read

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
        
      #- name: Build with Maven
      #  run: cd service-a && mvn -B package --file pom.xml
        #run: mvn -B package -pl service-a
        
      - name: Build with Gradle
        run: chmod +x service-a/gradlew && service-a/gradlew build
    
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
