name: Pipeline Lab Final Byron

on:
  push:
    branches: 
      - feature*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Analyze with SonarCloud
        run: |
          cd service-a
          chmod +x mvnw
          ./mvnw -B verify sonar:sonar -Dsonar.projectKey=bsmlazo_mavengradle-based-multi-module-spring-boot-microservices -Dsonar.organization=bsmlazo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Check Sonar Status
        uses: sonarcloud-actions/sonarcloud-check-status-action@v1
        with:
          branch: feature-ms-byronsanmartin-labfinal
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Build with Maven
        run: |
          cd service-a
          mvn -B package --file pom.xml
        
      #- name: Build with Gradle
      #  run: chmod +x service-a/gradlew && service-a/gradlew build
    
      #- name: SonarCloud Scan
      #  uses: sonarsource/sonarcloud-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          cd service-a
          docker build --compress -t bsanmartin:latest .
          docker push bsanmartin:latest
